# Generated by Django 4.0.1 on 2022-01-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Military',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=45, verbose_name='Номер')),
                ('dislocation', models.CharField(max_length=45, verbose_name='Дислокация')),
                ('type_troops', models.CharField(max_length=45, verbose_name='Вид войск')),
                ('companies', models.CharField(max_length=45, verbose_name='Роты')),
            ],
        ),
    ]
