# Generated by Django 4.0.2 on 2022-02-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45, verbose_name='Название')),
                ('number_employees', models.CharField(max_length=45, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Рота',
                'verbose_name_plural': 'Роты',
            },
        ),
        migrations.CreateModel(
            name='Military',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=45, verbose_name='Номер')),
                ('dislocation', models.CharField(max_length=45, verbose_name='Дислокация')),
                ('type_troops', models.CharField(max_length=45, verbose_name='Вид войск')),
                ('companies', models.CharField(max_length=45, verbose_name='Роты')),
            ],
            options={
                'verbose_name': 'Военная часть',
                'verbose_name_plural': 'Военные части',
            },
        ),
        migrations.CreateModel(
            name='Type_troop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45, verbose_name='Номер')),
                ('military', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.military')),
            ],
            options={
                'verbose_name': 'Виды войск',
                'verbose_name_plural': 'Виды войск',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fist_name', models.CharField(max_length=45, verbose_name='Имя')),
                ('companies', models.CharField(max_length=45, verbose_name='Рота')),
                ('post', models.CharField(max_length=45, verbose_name='Название')),
                ('year_birth', models.DateField()),
                ('year_enlistment', models.DateField()),
                ('length_service', models.CharField(max_length=45, verbose_name='Название')),
                ('honors', models.CharField(max_length=45, verbose_name='Название')),
                ('military_activies', models.CharField(max_length=45, verbose_name='Название')),
                ('compain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.companies')),
            ],
            options={
                'verbose_name': 'Личный состав',
                'verbose_name_plural': 'Личный состав',
            },
        ),
        migrations.CreateModel(
            name='Dislocatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=45, verbose_name='Название')),
                ('city', models.CharField(max_length=45, verbose_name='Название')),
                ('address', models.CharField(max_length=45, verbose_name='Название')),
                ('squar', models.CharField(max_length=45, verbose_name='Название')),
                ('military', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.military')),
            ],
            options={
                'verbose_name': 'Дислокация',
                'verbose_name_plural': 'Дислокация',
            },
        ),
        migrations.AddField(
            model_name='companies',
            name='type_troops',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.type_troop'),
        ),
    ]
