# Generated by Django 4.0.1 on 2022-01-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Название')),
                ('number_employees', models.CharField(max_length=45, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Рота',
                'verbose_name_plural': 'Роты',
            },
        ),
        migrations.CreateModel(
            name='Dislocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=45, verbose_name='Название')),
                ('city', models.CharField(max_length=45, verbose_name='Название')),
                ('address', models.CharField(max_length=45, verbose_name='Название')),
                ('squar', models.CharField(max_length=45, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Дислокация',
                'verbose_name_plural': 'Дислокация',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=45, verbose_name='Имя')),
                ('companies', models.CharField(max_length=45, verbose_name='Рота')),
                ('post', models.CharField(max_length=45, verbose_name='Название')),
                ('year_birth', models.DateField()),
                ('year_enlistment', models.DateField()),
                ('length_service', models.CharField(max_length=45, verbose_name='Название')),
                ('honors', models.CharField(max_length=45, verbose_name='Название')),
                ('military_activies', models.CharField(max_length=45, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Личный состав',
                'verbose_name_plural': 'Личный состав',
            },
        ),
        migrations.CreateModel(
            name='Type_troops',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Виды войск',
                'verbose_name_plural': 'Виды войск',
            },
        ),
        migrations.AlterModelOptions(
            name='military',
            options={'verbose_name': 'Военная часть', 'verbose_name_plural': 'Военные части'},
        ),
        migrations.AlterField(
            model_name='military',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
