# Generated by Django 4.0.1 on 2022-01-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='military',
            options={'verbose_name': 'Военная часть', 'verbose_name_plural': 'Военные части'},
        ),
    ]
