# Generated by Django 4.0.1 on 2022-02-01 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_companies_dislocation_employees_type_troops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='compain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.companies'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dislocation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
