# Generated by Django 4.0.1 on 2022-01-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_companies_dislocation_employees_type_troops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_troops',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Номер'),
        ),
    ]
