# Generated by Django 4.0.1 on 2022-02-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employees_compain_alter_companies_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='compain',
        ),
    ]
