# Generated by Django 4.0.1 on 2022-01-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_type_troops_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_troops',
            name='title',
            field=models.CharField(max_length=45, verbose_name='Номер'),
        ),
    ]
