# Generated by Django 4.0.1 on 2022-02-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_employees_compain'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='compain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.companies'),
        ),
    ]
