# Generated by Django 4.0.1 on 2022-02-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employees_compain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_troop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45, verbose_name='Номер')),
                ('military', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.military')),
            ],
            options={
                'verbose_name': 'Виды войск',
                'verbose_name_plural': 'Виды войск',
            },
        ),
        migrations.DeleteModel(
            name='Type_troops',
        ),
    ]
