# Generated by Django 4.0.1 on 2022-02-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_type_troop_delete_type_troops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislocatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=45, verbose_name='Название')),
                ('city', models.CharField(max_length=45, verbose_name='Название')),
                ('address', models.CharField(max_length=45, verbose_name='Название')),
                ('squar', models.CharField(max_length=45, verbose_name='Название')),
                ('military', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.military')),
            ],
            options={
                'verbose_name': 'Дислокация',
                'verbose_name_plural': 'Дислокация',
            },
        ),
        migrations.DeleteModel(
            name='Dislocation',
        ),
        migrations.AddField(
            model_name='companies',
            name='type_troops',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.type_troop'),
        ),
    ]
